version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - alpha-blog-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: alphaBlog@5512
      MYSQL_DATABASE: alpha-blog_db
    ports:
      - "13306:3306" 

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/alpha-blog
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    links:
      - db

volumes:
  alpha-blog-data: